-- Core client tables
CREATE TABLE `client_header` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `register_no` VARCHAR(6) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `person` VARCHAR(5) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `rcpt_flag` TINYINT NOT NULL DEFAULT 1,
  `rcpt_no` VARCHAR(13) NOT NULL,
  `rcpt_name` VARCHAR(20) NOT NULL,
  `rcpt_mail` VARCHAR(255) NOT NULL,
  `settle_flag` TINYINT NOT NULL DEFAULT 1,
  `desk_yn` BOOLEAN NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `client_rooms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` MEDIUMINT UNSIGNED NOT NULL,
  `building_id` TINYINT NOT NULL,
  `room_no` VARCHAR(4) NOT NULL,
  `central_password` VARCHAR(20) NULL,
  `door_password` VARCHAR(10) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `room_count` TINYINT NOT NULL DEFAULT 1,
  `bed_count` TINYINT NOT NULL DEFAULT 1,
  `checkout_time` TIME NOT NULL,
  `checkin_time` TIME NOT NULL,
  `facility_yn` BOOLEAN NOT NULL DEFAULT 1,
  `settle_flag` TINYINT NOT NULL DEFAULT 1,
  `ical_url_1` VARCHAR(2083) NULL,
  `ical_url_2` VARCHAR(2083) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ops tables (부분 발췌)
CREATE TABLE `work_header` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `room` INT NOT NULL,
  `cleaner_id` INT NULL,
  `butler_id` INT NULL,
  `amenities_qty` TINYINT NOT NULL,
  `blanket_qty` TINYINT NOT NULL,
  `conditionCheckYn` BOOLEAN NOT NULL DEFAULT 0,
  `cleaning_yn` BOOLEAN NOT NULL DEFAULT 1,
  `checkin_time` TIME NOT NULL,
  `ceckout_time` TIME NOT NULL,
  `supply_yn` BOOLEAN NOT NULL DEFAULT 1,
  `clening_flag` TINYINT NOT NULL DEFAULT 1,
  `requirements` VARCHAR(30) NULL,
  `cancel_yn` BOOLEAN NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `worker_header` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `register_no` VARCHAR(6) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(11) NULL,
  `reg_no` CHAR(13) NULL,
  `basecode_bank` VARCHAR(10) NULL,
  `basecode_code` VARCHAR(255) NULL,
  `account_no` VARCHAR(50) NULL,
  `rank` TINYINT NOT NULL,
  `tier` TINYINT NOT NULL DEFAULT 3,
  `comments` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `worker_evaluateHistory` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `worker_id` INT UNSIGNED NOT NULL,
  `evaluate_dttm` DATETIME NOT NULL,
  `work_id` BIGINT NOT NULL,
  `checklist_title_array` JSON NOT NULL,
  `checklist_point_sum` TINYINT NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 나머지 테이블은 batchs/schema.sql 참고
