-- Auto-generated by schema_create.py
-- Generated at: 2025-12-16 02:07:01

-- client_additional_price
DROP TABLE IF EXISTS `client_additional_price`;
CREATE TABLE `client_additional_price` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `room_id` int NOT NULL,
  `date` date NOT NULL,
  `seq` tinyint NOT NULL,
  `qty` smallint NOT NULL DEFAULT (0),
  `minus_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:양수 / 1:음수',
  `ratio_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:절대값 / 1:퍼센타일비율',
  `title` varchar(15) NOT NULL,
  `amount` decimal(9,2) NOT NULL,
  `comment` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cap_room_date` (`room_id`,`date`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- client_detail
DROP TABLE IF EXISTS `client_detail`;
CREATE TABLE `client_detail` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `client_id` mediumint unsigned NOT NULL COMMENT 'client_header 참조',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_client_detail_client_id` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- client_header
DROP TABLE IF EXISTS `client_header`;
CREATE TABLE `client_header` (
  `id` mediumint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `register_no` varchar(6) NOT NULL COMMENT '영대문자,숫자섞어서 랜덤생성/중복불가',
  `name` varchar(10) NOT NULL,
  `person` varchar(5) NOT NULL,
  `phone` varchar(11) NOT NULL COMMENT '휴대전화만 가능',
  `rcpt_flag` tinyint NOT NULL DEFAULT '1' COMMENT '1:세금계산서/2:현금영수증',
  `rcpt_no` varchar(13) DEFAULT NULL COMMENT '사업자번호,주민번호/숫자만',
  `rcpt_name` varchar(20) DEFAULT NULL COMMENT '영수증발행 대상의 이름',
  `rcpt_mail` varchar(255) DEFAULT NULL COMMENT '영수증 발행 받을 메일주소',
  `settle_flag` tinyint NOT NULL DEFAULT '1' COMMENT '1:건별제/2:정액제/3:커스텀/4:기타',
  `desk_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:사용안함/1:사용함',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_register_no_phone` (`register_no`,`phone`),
  KEY `idx_client_header_name` (`name`),
  KEY `idx_client_header_register_no` (`register_no`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- client_price_list
DROP TABLE IF EXISTS `client_price_list`;
CREATE TABLE `client_price_list` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `title` varchar(15) NOT NULL,
  `selected_by` tinyint NOT NULL COMMENT '1:client_price_set / 2:client_rooms / 3:client_additional_price',
  `minus_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:양수 / 1:음수',
  `ratio_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:절대값 / 1:퍼센타일비율',
  `per_bed_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:상관없음/1:침대당비용',
  `per_room_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:상관없음/1:방당비용',
  `type` tinyint NOT NULL COMMENT '1:횟수당 / 2:월당',
  `amount` decimal(11,2) NOT NULL,
  `dscpt` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- client_price_set_detail
DROP TABLE IF EXISTS `client_price_set_detail`;
CREATE TABLE `client_price_set_detail` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `price_set_id` int DEFAULT NULL,
  `price_id` int DEFAULT NULL,
  `minus_yn` tinyint(1) DEFAULT NULL COMMENT '0:양수 / 1:음수',
  `ratio_yn` tinyint(1) DEFAULT NULL COMMENT '0:절대값 / 1:퍼센타일비율',
  `amount_per_cleaning` decimal(9,2) DEFAULT NULL,
  `amount_per_month` decimal(11,2) DEFAULT NULL,
  `use_yn` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0:사용안함 / 1:사용함',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_price_set_detail` (`price_set_id`,`price_id`),
  KEY `idx_price_set_price_set_header` (`price_set_id`),
  KEY `idx_price_set_price_list` (`price_id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- client_price_set_header
DROP TABLE IF EXISTS `client_price_set_header`;
CREATE TABLE `client_price_set_header` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `title` varchar(15) DEFAULT NULL,
  `dscpt` varchar(50) DEFAULT NULL,
  `use_yn` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0:사용안함 / 1:사용함',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- client_rooms
DROP TABLE IF EXISTS `client_rooms`;
CREATE TABLE `client_rooms` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `client_id` mediumint unsigned NOT NULL COMMENT 'client_header 참조',
  `building_id` tinyint NOT NULL,
  `room_no` char(5) NOT NULL,
  `central_password` varchar(20) DEFAULT NULL,
  `door_password` varchar(15) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `open_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:운영안함, 1:운영함',
  `room_count` tinyint NOT NULL DEFAULT '1',
  `bed_count` tinyint NOT NULL DEFAULT '1',
  `checkout_time` time NOT NULL,
  `checkin_time` time NOT NULL,
  `price_set_id` int NOT NULL,
  `images_set_id` int NOT NULL,
  `checklist_set_id` int NOT NULL,
  `facility_yn` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0:사용안함/1:사용함',
  `realtime_overview_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:사용안함/1:사용함',
  `images_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:사용안함/1:사용함',
  `ical_url_1` varchar(2083) DEFAULT NULL,
  `ical_url_2` varchar(2083) DEFAULT NULL,
  `weight` tinyint NOT NULL DEFAULT '10',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_client_rooms_client` (`client_id`),
  KEY `idx_client_rooms_client_open` (`client_id`,`open_yn`),
  KEY `idx_building_room` (`building_id`,`room_no`),
  KEY `idx_client_rooms_building_id` (`building_id`),
  KEY `idx_client_rooms_price_set` (`price_set_id`),
  KEY `idx_client_rooms_images_set` (`images_set_id`),
  KEY `idx_client_rooms_checklist_set` (`checklist_set_id`)
) ENGINE=InnoDB AUTO_INCREMENT=107 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- client_supplements
DROP TABLE IF EXISTS `client_supplements`;
CREATE TABLE `client_supplements` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `room_id` int NOT NULL,
  `date` date NOT NULL,
  `next_date` date DEFAULT NULL,
  `title` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `dscpt` varchar(2083) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `buy_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:구매안함, 1:구매함',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=216 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- etc_baseCode
DROP TABLE IF EXISTS `etc_baseCode`;
CREATE TABLE `etc_baseCode` (
  `code_group` varchar(30) NOT NULL COMMENT '코드그룹명',
  `code` varchar(10) NOT NULL COMMENT '코드',
  `value` varchar(255) NOT NULL COMMENT '값',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`code_group`,`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- etc_buildings
DROP TABLE IF EXISTS `etc_buildings`;
CREATE TABLE `etc_buildings` (
  `id` tinyint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `basecode_sector` varchar(10) NOT NULL COMMENT '지역코드',
  `basecode_code` varchar(255) NOT NULL COMMENT '지역값',
  `building_name` varchar(20) NOT NULL,
  `building_short_name` varchar(10) NOT NULL,
  `building_address_old` varchar(255) NOT NULL,
  `building_address_new` varchar(255) NOT NULL,
  `building_password` varchar(10) DEFAULT NULL,
  `building_recycle` varchar(20) DEFAULT NULL,
  `building_general` varchar(20) DEFAULT NULL,
  `building_food` varchar(20) DEFAULT NULL,
  `building_way_img_basePath` varchar(255) DEFAULT NULL,
  `building_way_img_relativePath` varchar(255) DEFAULT NULL,
  `delete_yn` tinyint(1) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_buildings_region` (`basecode_sector`,`basecode_code`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- etc_errorLogs
DROP TABLE IF EXISTS `etc_errorLogs`;
CREATE TABLE `etc_errorLogs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `level` tinyint unsigned NOT NULL COMMENT '1:FATAL/2:ERROR/3:WARN/4:INFO/5:DEBUG',
  `app_name` varchar(50) NOT NULL COMMENT '서비스 또는 모듈명',
  `error_code` varchar(50) DEFAULT NULL COMMENT '비즈니스 에러코드',
  `message` varchar(500) NOT NULL COMMENT '요약 에러 메시지',
  `stacktrace` text COMMENT '전체 스택 트레이스',
  `request_id` varchar(100) DEFAULT NULL COMMENT '트랜잭션/요청 추적용 ID',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '에러 발생 유저 PK',
  `context_json` json DEFAULT NULL COMMENT '추가 상태/파라미터 JSON',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_errorLogs_created_at` (`created_at`),
  KEY `idx_errorLogs_request_id` (`request_id`),
  KEY `idx_errorLogs_user` (`user_id`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=422 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- etc_errorLogs_batch
DROP TABLE IF EXISTS `etc_errorLogs_batch`;
CREATE TABLE `etc_errorLogs_batch` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `level` tinyint unsigned DEFAULT NULL COMMENT '1:FATAL/2:ERROR/3:WARN/4:INFO/5:DEBUG',
  `app_name` varchar(50) NOT NULL COMMENT '서비스 또는 모듈 또는 프로그램 명',
  `error_code` varchar(50) DEFAULT NULL COMMENT '비즈니스 에러코드',
  `message` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '요약 에러 메시지',
  `stacktrace` text COMMENT '전체 스택 트레이스',
  `request_id` varchar(100) DEFAULT NULL COMMENT '트랜잭션/요청 추적용 ID',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '에러 발생 유저 PK',
  `context_json` json DEFAULT NULL COMMENT '추가 상태/파라미터 JSON',
  `start_dttm` timestamp NOT NULL COMMENT '시작 dttm. 무조건 남는다.',
  `end_dttm` timestamp NOT NULL COMMENT '종료 dttm. 무조건 남는다.',
  `end_flag` tinyint(1) NOT NULL COMMENT '1:정상종료, 2:비정상종료',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- etc_notice
DROP TABLE IF EXISTS `etc_notice`;
CREATE TABLE `etc_notice` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `notice_date` date NOT NULL,
  `notice` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- kakao_channel_subscribers
DROP TABLE IF EXISTS `kakao_channel_subscribers`;
CREATE TABLE `kakao_channel_subscribers` (
  `id` bigint NOT NULL COMMENT 'PK',
  `user_type` enum('CLIENT','WORKER') NOT NULL,
  `user_id` bigint NOT NULL,
  `phone` varchar(20) NOT NULL,
  `kakao_user_uuid` varchar(64) DEFAULT NULL,
  `friend_status` enum('NONE','FRIEND') DEFAULT NULL,
  `ad_opt_in_yn` enum('Y','N') DEFAULT NULL,
  `opt_in_scope` enum('INFO','AD','BOTH') DEFAULT NULL,
  `opt_in_dttm` datetime DEFAULT NULL,
  `opt_out_dttm` datetime DEFAULT NULL,
  `consent_version` varchar(20) DEFAULT NULL,
  `source` enum('APP','WEB','QR','API') DEFAULT NULL,
  `last_sync_dttm` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user` (`user_type`,`user_id`),
  KEY `idx_phone` (`phone`),
  KEY `idx_kakao_uuid` (`kakao_user_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- kakao_message_logs
DROP TABLE IF EXISTS `kakao_message_logs`;
CREATE TABLE `kakao_message_logs` (
  `id` bigint NOT NULL,
  `user_type` enum('CLIENT','WORKER') NOT NULL,
  `user_id` bigint NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `kakao_user_uuid` varchar(64) DEFAULT NULL,
  `template_code` varchar(50) NOT NULL,
  `payload_json` json NOT NULL,
  `status` enum('QUEUED','SENT','DELIVERED','FAILED') NOT NULL,
  `provider_message_id` varchar(100) DEFAULT NULL,
  `error_code` varchar(50) DEFAULT NULL,
  `ad_yn` enum('Y','N') DEFAULT NULL,
  `sent_at` datetime DEFAULT NULL,
  `delivered_at` datetime DEFAULT NULL,
  `failed_at` datetime DEFAULT NULL,
  `price` int DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_type`,`user_id`),
  KEY `idx_template` (`template_code`),
  KEY `idx_kakao_uuid` (`kakao_user_uuid`),
  KEY `idx_status` (`status`),
  KEY `idx_sent_at` (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- kakao_optout_logs
DROP TABLE IF EXISTS `kakao_optout_logs`;
CREATE TABLE `kakao_optout_logs` (
  `id` bigint NOT NULL,
  `user_type` enum('CLIENT','WORKER') NOT NULL,
  `user_id` bigint NOT NULL,
  `action` enum('OPT_IN','OPT_OUT') NOT NULL,
  `reason` varchar(200) DEFAULT NULL,
  `source` enum('APP','WEB','MESSAGE','ADMIN') DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_type`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- kakao_templates
DROP TABLE IF EXISTS `kakao_templates`;
CREATE TABLE `kakao_templates` (
  `id` bigint NOT NULL,
  `template_code` varchar(50) NOT NULL,
  `category` enum('ALIMTALK','FRIENDTALK','CHANNEL_1TO1') NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `body` text NOT NULL,
  `button_json` json DEFAULT NULL,
  `ad_yn` enum('Y','N') DEFAULT NULL,
  `sender_key` varchar(100) DEFAULT NULL,
  `channel_id` varchar(100) DEFAULT NULL,
  `rest_api_key` varchar(200) DEFAULT NULL,
  `client_secret` varchar(200) DEFAULT NULL,
  `use_yn` enum('Y','N') NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template_code` (`template_code`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- model_variable
DROP TABLE IF EXISTS `model_variable`;
CREATE TABLE `model_variable` (
  `name` varchar(32) NOT NULL,
  `value` double NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- notify_jobs
DROP TABLE IF EXISTS `notify_jobs`;
CREATE TABLE `notify_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `rule_code` varchar(50) NOT NULL,
  `user_type` enum('CLIENT','WORKER') NOT NULL,
  `user_id` bigint NOT NULL,
  `scheduled_at` datetime NOT NULL,
  `dedup_key` varchar(120) NOT NULL,
  `payload_json` json NOT NULL,
  `status` enum('READY','LOCKED','DONE','FAILED') NOT NULL DEFAULT 'READY',
  `try_count` tinyint unsigned NOT NULL DEFAULT '0',
  `last_error` varchar(255) DEFAULT NULL,
  `locked_at` datetime DEFAULT NULL,
  `locked_by` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notify_jobs_dedup` (`dedup_key`),
  KEY `idx_notify_jobs_pick` (`status`,`scheduled_at`),
  KEY `idx_notify_jobs_user` (`user_type`,`user_id`,`scheduled_at`),
  KEY `idx_notify_jobs_rule` (`rule_code`,`scheduled_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- notify_rules
DROP TABLE IF EXISTS `notify_rules`;
CREATE TABLE `notify_rules` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `rule_code` varchar(50) NOT NULL,
  `channel` enum('WEBPUSH') NOT NULL DEFAULT 'WEBPUSH',
  `template_code` varchar(50) NOT NULL,
  `enabled_yn` tinyint(1) NOT NULL DEFAULT '1',
  `schedule_cron` varchar(50) DEFAULT NULL,
  `event_type` varchar(50) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notify_rules_rule_code` (`rule_code`),
  KEY `idx_notify_rules_enabled` (`enabled_yn`),
  KEY `idx_notify_rules_template` (`template_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- push_message_logs
DROP TABLE IF EXISTS `push_message_logs`;
CREATE TABLE `push_message_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `notify_job_id` bigint unsigned NOT NULL,
  `subscription_id` bigint unsigned NOT NULL,
  `status` enum('QUEUED','SENT','FAILED','EXPIRED') NOT NULL DEFAULT 'QUEUED',
  `http_status` smallint unsigned DEFAULT NULL,
  `error_code` varchar(50) DEFAULT NULL,
  `error_message` varchar(255) DEFAULT NULL,
  `sent_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_push_logs_job` (`notify_job_id`),
  KEY `idx_push_logs_sub` (`subscription_id`),
  KEY `idx_push_logs_status` (`status`,`sent_at`),
  CONSTRAINT `fk_push_logs_job` FOREIGN KEY (`notify_job_id`) REFERENCES `notify_jobs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_push_logs_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `push_subscriptions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- push_subscriptions
DROP TABLE IF EXISTS `push_subscriptions`;
CREATE TABLE `push_subscriptions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_type` enum('CLIENT','WORKER') NOT NULL,
  `user_id` int DEFAULT NULL,
  `endpoint` varchar(2083) NOT NULL,
  `p256dh` varchar(255) NOT NULL,
  `auth` varchar(255) NOT NULL,
  `enabled_yn` tinyint(1) NOT NULL DEFAULT '1',
  `last_seen_at` datetime DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `platform` varchar(50) DEFAULT NULL,
  `browser` varchar(50) DEFAULT NULL,
  `device_id` varchar(100) DEFAULT NULL,
  `locale` varchar(10) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_webpush_endpoint` (`user_type`,`endpoint`(255),`user_id`) USING BTREE,
  KEY `idx_webpush_last_seen` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- push_templates
DROP TABLE IF EXISTS `push_templates`;
CREATE TABLE `push_templates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `template_code` varchar(50) NOT NULL,
  `title` varchar(100) NOT NULL,
  `body` text NOT NULL,
  `icon_url` varchar(2083) DEFAULT NULL,
  `click_url` varchar(2083) DEFAULT NULL,
  `action_json` json DEFAULT NULL,
  `ttl_sec` int unsigned NOT NULL DEFAULT '3600',
  `urgency` enum('very-low','low','normal','high') NOT NULL DEFAULT 'normal',
  `use_yn` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_push_template_code` (`template_code`),
  KEY `idx_push_templates_use` (`use_yn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_apply
DROP TABLE IF EXISTS `work_apply`;
CREATE TABLE `work_apply` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `work_date` date NOT NULL,
  `basecode_sector` varchar(10) NOT NULL COMMENT '지역코드',
  `basecode_code` varchar(255) NOT NULL COMMENT '지역값',
  `seq` tinyint NOT NULL,
  `position` tinyint NOT NULL COMMENT '1:클리너/2:버틀러',
  `worker_id` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_work_apply` (`work_date`,`worker_id`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_apply_rules
DROP TABLE IF EXISTS `work_apply_rules`;
CREATE TABLE `work_apply_rules` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `min_weight` smallint NOT NULL,
  `max_weight` smallint NOT NULL,
  `cleaner_count` tinyint NOT NULL,
  `butler_count` tinyint NOT NULL,
  `level_flag` tinyint NOT NULL DEFAULT '1' COMMENT '1:normal/2:warning/3:emergency',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_assignment
DROP TABLE IF EXISTS `work_assignment`;
CREATE TABLE `work_assignment` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `work_id` bigint NOT NULL,
  `worker_id` int NOT NULL,
  `assign_dttm` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_work_assignment_work_id` (`work_id`),
  KEY `idx_work_assignment_worker_id` (`worker_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_checklist_list
DROP TABLE IF EXISTS `work_checklist_list`;
CREATE TABLE `work_checklist_list` (
  `id` tinyint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `type` tinyint NOT NULL COMMENT '1:cleaning/2:supervising/3:supplies',
  `ordering` tinyint NOT NULL,
  `title` varchar(20) NOT NULL,
  `dscpt` varchar(2083) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `score` tinyint DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_checklist_set_detail
DROP TABLE IF EXISTS `work_checklist_set_detail`;
CREATE TABLE `work_checklist_set_detail` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `checklist_list_id` tinyint NOT NULL,
  `checklist_header_id` int NOT NULL,
  `ordering` tinyint DEFAULT NULL,
  `title` varchar(20) DEFAULT NULL,
  `dscpt` varchar(50) DEFAULT NULL,
  `score` tinyint DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_checklist_set_detail` (`checklist_header_id`,`checklist_list_id`),
  KEY `idx_work_checklist_set_work_checklist_set__header` (`checklist_header_id`),
  KEY `idx_work_checklist_set_work_checklist_set__list` (`checklist_list_id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_checklist_set_header
DROP TABLE IF EXISTS `work_checklist_set_header`;
CREATE TABLE `work_checklist_set_header` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `title` varchar(15) NOT NULL,
  `dscpt` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_fore_accuracy
DROP TABLE IF EXISTS `work_fore_accuracy`;
CREATE TABLE `work_fore_accuracy` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `date` date NOT NULL,
  `horizon` char(3) NOT NULL,
  `acc` decimal(5,4) NOT NULL,
  `prec` decimal(5,4) NOT NULL,
  `rec` decimal(5,4) NOT NULL,
  `f1` decimal(5,4) NOT NULL,
  `n` tinyint NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_wfa_date_horizon` (`date`,`horizon`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_fore_d1
DROP TABLE IF EXISTS `work_fore_d1`;
CREATE TABLE `work_fore_d1` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `run_dttm` date NOT NULL,
  `target_date` date NOT NULL,
  `room_id` int NOT NULL,
  `p_out` decimal(4,3) NOT NULL,
  `actual_out` tinyint(1) NOT NULL,
  `correct` tinyint(1) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_work_fore_d1_room_id` (`room_id`),
  KEY `idx_work_fore_d1_run` (`run_dttm`),
  KEY `idx_work_fore_d1_target_room` (`target_date`,`room_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4867 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_fore_d7
DROP TABLE IF EXISTS `work_fore_d7`;
CREATE TABLE `work_fore_d7` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `run_dttm` date NOT NULL,
  `target_date` date NOT NULL,
  `room_id` int NOT NULL,
  `p_out` decimal(4,3) NOT NULL,
  `actual_out` tinyint(1) NOT NULL,
  `correct` tinyint(1) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_work_fore_d7_room_id` (`room_id`),
  KEY `idx_work_fore_d7_run` (`run_dttm`),
  KEY `idx_work_fore_d7_target_room` (`target_date`,`room_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5269 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_fore_tuning
DROP TABLE IF EXISTS `work_fore_tuning`;
CREATE TABLE `work_fore_tuning` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `date` date NOT NULL,
  `horizon` char(3) NOT NULL,
  `variable` varchar(15) NOT NULL,
  `before` decimal(5,4) NOT NULL,
  `after` decimal(5,4) NOT NULL,
  `delta` decimal(10,6) NOT NULL,
  `explanation` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_wft_date_horizon` (`date`,`horizon`),
  KEY `idx_wft_variable` (`variable`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_fore_variable
DROP TABLE IF EXISTS `work_fore_variable`;
CREATE TABLE `work_fore_variable` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `name` varchar(15) NOT NULL,
  `value` decimal(5,4) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_wfv_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_global_detail
DROP TABLE IF EXISTS `work_global_detail`;
CREATE TABLE `work_global_detail` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `work_global_id` tinyint NOT NULL DEFAULT (0),
  `room_id` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_work_global_id_room_id` (`work_global_id`,`room_id`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_global_header
DROP TABLE IF EXISTS `work_global_header`;
CREATE TABLE `work_global_header` (
  `id` tinyint unsigned NOT NULL DEFAULT (0) COMMENT 'PK',
  `emoji` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(20) NOT NULL,
  `dscpt` varchar(50) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `remain_qty` tinyint NOT NULL,
  `closed_yn` tinyint(1) NOT NULL DEFAULT '0',
  `comment` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_header
DROP TABLE IF EXISTS `work_header`;
CREATE TABLE `work_header` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `date` date NOT NULL,
  `room_id` int NOT NULL,
  `cleaner_id` int DEFAULT NULL,
  `butler_id` int DEFAULT NULL,
  `amenities_qty` tinyint NOT NULL,
  `blanket_qty` tinyint NOT NULL,
  `condition_check_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:대상아님/1:대상',
  `cleaning_yn` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0:대상아님/1:대상',
  `checkin_time` time NOT NULL,
  `checkout_time` time NOT NULL,
  `supply_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:미배급/1:배급',
  `clening_flag` tinyint NOT NULL DEFAULT '1' COMMENT '1:대기/2:시작/3:완료5분전/4:완료',
  `supervising_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:수퍼바이징미완료 / 1:수퍼바이징완료',
  `cleaning_end_time` time DEFAULT NULL,
  `supervising_end_time` time DEFAULT NULL,
  `requirements` varchar(30) DEFAULT NULL,
  `cancel_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:정상/1:취소',
  `manual_upt_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:수동조작없음/1:수동조작있음',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_work_header_date_room_id` (`date`,`room_id`),
  KEY `idx_work_header_butler` (`date`,`butler_id`),
  KEY `idx_work_header_cleaner` (`date`,`cleaner_id`),
  KEY `idx_work_header_room` (`date`,`room_id`),
  KEY `idx_work_header_butler_id` (`butler_id`),
  KEY `idx_work_header_cleaner_id` (`cleaner_id`),
  KEY `idx_work_header_room_id` (`room_id`)
) ENGINE=InnoDB AUTO_INCREMENT=350 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_images_list
DROP TABLE IF EXISTS `work_images_list`;
CREATE TABLE `work_images_list` (
  `id` tinyint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `title` varchar(15) NOT NULL,
  `ordering` tinyint NOT NULL,
  `comment` varchar(50) DEFAULT NULL,
  `required` tinyint(1) NOT NULL COMMENT '0:선택 / 1:필수',
  `role` tinyint NOT NULL COMMENT '1:클리너 / 2:버틀러/3:상태확인',
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_images_set_detail
DROP TABLE IF EXISTS `work_images_set_detail`;
CREATE TABLE `work_images_set_detail` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `images_set_id` int NOT NULL,
  `images_list_id` tinyint NOT NULL,
  `ordering` tinyint NOT NULL,
  `required` tinyint(1) DEFAULT NULL COMMENT '0:선택 / 1:필수',
  `role` tinyint DEFAULT NULL COMMENT '1:클리너 / 2:버틀러',
  `title` varchar(15) DEFAULT NULL,
  `comment` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_images_set_detail` (`images_set_id`,`images_list_id`),
  KEY `idx_images_set_image_set_header` (`images_set_id`),
  KEY `idx_images_set_images_list` (`images_list_id`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_images_set_header
DROP TABLE IF EXISTS `work_images_set_header`;
CREATE TABLE `work_images_set_header` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `title` varchar(15) NOT NULL,
  `dscpt` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_reports
DROP TABLE IF EXISTS `work_reports`;
CREATE TABLE `work_reports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `work_id` bigint NOT NULL,
  `type` tinyint NOT NULL COMMENT '1:cleaningChecklist/2:supplies/3:cleaningImages/4:supervisingChecklist/5:supervisingImages/6:workdttm/7:conditionCheckImages',
  `contents1` json NOT NULL,
  `contents2` json DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_work_reports_work_type` (`work_id`,`type`),
  KEY `idx_work_reports_work_id` (`work_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1287 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- work_reservation
DROP TABLE IF EXISTS `work_reservation`;
CREATE TABLE `work_reservation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `work_id` bigint DEFAULT NULL,
  `room_id` int NOT NULL,
  `amenities_qty` tinyint NOT NULL,
  `blanket_qty` tinyint NOT NULL,
  `checkin_time` time NOT NULL,
  `checkout_time` time NOT NULL,
  `requirements` varchar(30) DEFAULT NULL,
  `cancel_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:정상/1:취소',
  `reflect_yn` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_detail
DROP TABLE IF EXISTS `worker_detail`;
CREATE TABLE `worker_detail` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `worker_id` bigint unsigned NOT NULL COMMENT 'client_header 참조',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_worker_detail_worker` (`worker_id`),
  KEY `idx_worker_detail_worker_id` (`worker_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_evaluateHistory
DROP TABLE IF EXISTS `worker_evaluateHistory`;
CREATE TABLE `worker_evaluateHistory` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `worker_id` int unsigned NOT NULL COMMENT 'client_header 참조',
  `evaluate_dttm` datetime NOT NULL,
  `work_id` bigint NOT NULL,
  `checklist_title_array` json NOT NULL,
  `checklist_point_sum` tinyint NOT NULL,
  `comment` varchar(255) NOT NULL COMMENT '당일의 마지막 청소 건에만 입력',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_weh_work` (`work_id`),
  KEY `idx_weh_worker_date` (`worker_id`,`evaluate_dttm`),
  KEY `idx_worker_evaluateHistory_worker_id` (`worker_id`)
) ENGINE=InnoDB AUTO_INCREMENT=204 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_header
DROP TABLE IF EXISTS `worker_header`;
CREATE TABLE `worker_header` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `register_no` varchar(6) NOT NULL COMMENT '영대문자,숫자섞어서 랜덤생성/중복불가',
  `name` varchar(20) NOT NULL,
  `phone` varchar(11) DEFAULT NULL COMMENT '휴대전화만 가능',
  `reg_no` char(13) DEFAULT NULL,
  `basecode_bank` varchar(10) DEFAULT NULL COMMENT '지역코드',
  `basecode_code` varchar(255) DEFAULT NULL COMMENT '지역값',
  `account_no` varchar(50) DEFAULT NULL,
  `score_20days` smallint NOT NULL DEFAULT '0' COMMENT '20일간업무평점',
  `tier` tinyint NOT NULL,
  `comments` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_worker_header_register_no` (`register_no`),
  UNIQUE KEY `ux_worker_header_phone` (`phone`),
  KEY `idx_worker_header_phone` (`phone`),
  KEY `idx_worker_header_register_no` (`register_no`),
  KEY `idx_worker_header_tier` (`tier`)
) ENGINE=InnoDB AUTO_INCREMENT=130 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_penaltyHistory
DROP TABLE IF EXISTS `worker_penaltyHistory`;
CREATE TABLE `worker_penaltyHistory` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `worker_id` int unsigned NOT NULL COMMENT 'client_header 참조',
  `start_date` date NOT NULL,
  `interval` tinyint NOT NULL,
  `comment` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_wph_worker_start` (`worker_id`,`start_date`),
  KEY `idx_worker_penaltyHistory_worker_id` (`worker_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_salary_history
DROP TABLE IF EXISTS `worker_salary_history`;
CREATE TABLE `worker_salary_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `worker_id` int unsigned NOT NULL COMMENT 'worker_header참조',
  `work_date` date NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `tier_target_date` tinyint NOT NULL,
  `hourly_wage_target_date` smallint NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_schedule_exception
DROP TABLE IF EXISTS `worker_schedule_exception`;
CREATE TABLE `worker_schedule_exception` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `worker_id` int unsigned NOT NULL COMMENT 'client_header 참조',
  `excpt_date` date NOT NULL COMMENT '0:일요일 ~ 6:토요일',
  `add_work_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:규칙대로/1:무조건출근',
  `cancel_work_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:규칙대로/1:무조건휴일',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_worker_schedule_exception` (`worker_id`,`excpt_date`),
  KEY `idx_worker_schedule_exception_worker_id` (`worker_id`),
  KEY `ck_wse_logic` (`add_work_yn`,`cancel_work_yn`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_tier_rules
DROP TABLE IF EXISTS `worker_tier_rules`;
CREATE TABLE `worker_tier_rules` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `min_percentage` tinyint unsigned NOT NULL,
  `max_percentage` tinyint NOT NULL,
  `tier` tinyint NOT NULL,
  `hourly_wage` smallint DEFAULT NULL,
  `apply_start_time` time DEFAULT NULL,
  `apply_horizon` tinyint DEFAULT NULL,
  `comment` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- worker_weekly_pattern
DROP TABLE IF EXISTS `worker_weekly_pattern`;
CREATE TABLE `worker_weekly_pattern` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `worker_id` int unsigned NOT NULL COMMENT 'client_header 참조',
  `weekday` tinyint NOT NULL COMMENT '0:일요일 ~ 6:토요일',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_worker_weekly_pattern` (`worker_id`,`weekday`),
  KEY `idx_worker_weekly_pattern_worker_id` (`worker_id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
